//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuizRegistration.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuizRegistration.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при авторизации! Проверьте введенный email и пароль!
        ///{
        ///
        ///0}.
        /// </summary>
        internal static string AuthorizationError {
            get {
                return ResourceManager.GetString("AuthorizationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отменить регистрацию.
        /// </summary>
        internal static string CancelRegistrationMsg {
            get {
                return ResourceManager.GetString("CancelRegistrationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Возникла ошибка при отмене игры, попробуйте еще раз!.
        /// </summary>
        internal static string ErrorGameCancellation {
            get {
                return ResourceManager.GetString("ErrorGameCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата игры: {0}.
        /// </summary>
        internal static string GameDateMsg {
            get {
                return ResourceManager.GetString("GameDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Место игры: {0} ({1}).
        /// </summary>
        internal static string GamePlaceMsg {
            get {
                return ResourceManager.GetString("GamePlaceMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список актуальных регистраций на игры.
        /// </summary>
        internal static string GamesTabTitle {
            get {
                return ResourceManager.GetString("GamesTabTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка при получении списка игр.
        /// </summary>
        internal static string GetGamesListError {
            get {
                return ResourceManager.GetString("GetGamesListError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка при получении данных пользователя! Статус код {0}.
        /// </summary>
        internal static string GetUserDataError {
            get {
                return ResourceManager.GetString("GetUserDataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка сети при получении данных пользователя {0}.
        /// </summary>
        internal static string NetworkError {
            get {
                return ResourceManager.GetString("NetworkError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нет регистраций на игры :(.
        /// </summary>
        internal static string NoRegistrationsMsg {
            get {
                return ResourceManager.GetString("NoRegistrationsMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество игроков: {0}.
        /// </summary>
        internal static string PlayersCountMsg {
            get {
                return ResourceManager.GetString("PlayersCountMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация: {0}.
        /// </summary>
        internal static string RegDateMsg {
            get {
                return ResourceManager.GetString("RegDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дата регистрации: {0}.
        /// </summary>
        internal static string RegistrationDateMsg {
            get {
                return ResourceManager.GetString("RegistrationDateMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурс {0} не найден..
        /// </summary>
        internal static string ResourseNotFoundError {
            get {
                return ResourceManager.GetString("ResourseNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка запуска приложения.
        /// </summary>
        internal static string RunApplicationErrorTitle {
            get {
                return ResourceManager.GetString("RunApplicationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите имя капитана!.
        /// </summary>
        internal static string SelectCaptainNameMsg {
            get {
                return ResourceManager.GetString("SelectCaptainNameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Укажите номер телефона капитана!.
        /// </summary>
        internal static string SelectCaptainPhoneMsg {
            get {
                return ResourceManager.GetString("SelectCaptainPhoneMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите игру!.
        /// </summary>
        internal static string SelectGameMsg {
            get {
                return ResourceManager.GetString("SelectGameMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите команду!.
        /// </summary>
        internal static string SelectTeamMsg {
            get {
                return ResourceManager.GetString("SelectTeamMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запрос регистрации на игру {0} отправлен. Регистрация откроется в {1}.
        ///
        ///.
        /// </summary>
        internal static string SendRegistrationMsg {
            get {
                return ResourceManager.GetString("SendRegistrationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка обработки ответа сервера.
        ///{0}.
        /// </summary>
        internal static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация на игру успешно отменена!.
        /// </summary>
        internal static string SuccessfulGameCancellation {
            get {
                return ResourceManager.GetString("SuccessfulGameCancellation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы успешно зарегистрировались на игру {0} в {1}
        ///
        ///.
        /// </summary>
        internal static string SuccessRegistrationMsg {
            get {
                return ResourceManager.GetString("SuccessRegistrationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошло неожиданное исключение. Программа завершает свою работу..
        /// </summary>
        internal static string UnhandledExceptionMsg {
            get {
                return ResourceManager.GetString("UnhandledExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный формат пользовательских данных, полученных с сервера {0}.
        /// </summary>
        internal static string UserDataFormatError {
            get {
                return ResourceManager.GetString("UserDataFormatError", resourceCulture);
            }
        }
    }
}
